name: Main CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0" # Assurez-vous de récupérer tous les fichiers et branches

      - name: Print working directory
        run: pwd

      - name: List files in working directory
        run: ls -la

      # Assurez-vous que le répertoire 'data' existe
      - name: Check if data directory exists
        run: |
          if [ -d "data" ]; then
            echo "Directory 'data' exists."
            ls -la data
          else
            echo "Directory 'data' does not exist."
            exit 1
          fi

      - name: Run tests
        run: python -m pytest tests/
